WORDING = \
    {
        'python_not_supported': 'Python version is not supported, upgrade to {version} or higher',
        'ffmpeg_not_installed': 'FFMpeg is not installed',
        'install_dependency_help': 'select the variant of {dependency} to install',
        'skip_venv_help': 'skip the virtual environment check',
        'source_help': 'select a source image',
        'target_help': 'select a target image or video',
        'output_help': 'specify the output file or directory',
        'frame_processors_help': 'choose from the available frame processors (choices: {choices}, ...)',
        'frame_processor_model_help': 'choose the model for the frame processor',
        'frame_processor_blend_help': 'specify the blend amount for the frame processor',
        'face_debugger_items_help': 'specify the face debugger items',
        'ui_layouts_help': 'choose from the available ui layouts (choices: {choices}, ...)',
        'keep_fps_help': 'preserve the frames per second (fps) of the target',
        'keep_temp_help': 'retain temporary frames after processing',
        'skip_audio_help': 'omit audio from the target',
        'face_analyser_order_help': 'specify the order used for the face analyser',
        'face_analyser_age_help': 'specify the age used for the face analyser',
        'face_analyser_gender_help': 'specify the gender used for the face analyser',
        'face_detector_model_help': 'specify the model used for the face detector',
        'face_detector_size_help': 'specify the size threshold used for the face detector',
        'face_detector_score_help': 'specify the score threshold used for the face detector',
        'face_selector_mode_help': 'specify the mode for the face selector',
        'reference_face_position_help': 'specify the position of the reference face',
        'reference_face_distance_help': 'specify the distance between the reference face and the target face',
        'reference_frame_number_help': 'specify the number of the reference frame',
        'face_mask_types_help': 'choose from the available face mask types',
        'face_mask_blur_help': 'specify the blur amount for face mask',
        'face_mask_padding_help': 'specify the face mask padding (top, right, bottom, left) in percent',
        'face_mask_regions_help': 'choose from the available face mask regions',
        'trim_frame_start_help': 'specify the start frame for extraction',
        'trim_frame_end_help': 'specify the end frame for extraction',
        'temp_frame_format_help': 'specify the image format used for frame extraction',
        'temp_frame_quality_help': 'specify the image quality used for frame extraction',
        'output_image_quality_help': 'specify the quality used for the output image',
        'output_video_encoder_help': 'specify the encoder used for the output video',
        'output_video_preset_help': 'specify the preset used for the output video',
        'output_video_quality_help': 'specify the quality used for the output video',
        'output_video_resolution_help': 'specify the resolution used for the output video',
        'output_video_fps_help': 'specify the frames per second (fps) used for the output video',
        'video_memory_strategy_help': 'specify strategy to handle the video memory',
        'max_memory_help': 'specify the maximum amount of ram to be used (in gb)',
        'execution_providers_help': 'choose from the available execution providers',
        'execution_thread_count_help': 'specify the number of execution threads',
        'execution_queue_count_help': 'specify the number of execution queries',
        'skip_download_help': 'omit automate downloads and lookups',
        'headless_help': 'run the program in headless mode',
        'log_level_help': 'choose from the available log levels',
        'creating_temp': 'Creating temporary resources',
        'extracting_frames_fps': 'Extracting frames with {fps} FPS',
        'analysing': 'Analysing',
        'processing': 'Processing',
        'downloading': 'Downloading',
        'temp_frames_not_found': 'Temporary frames not found',
        'compressing_image': 'Compressing image',
        'compressing_image_failed': 'Compressing image failed',
        'merging_video_fps': 'Merging video with {fps} FPS',
        'merging_video_failed': 'Merging video failed',
        'skipping_audio': 'Skipping audio',
        'restoring_audio': 'Restoring audio',
        'restoring_audio_skipped': 'Restoring audio skipped',
        'clearing_temp': 'Clearing temporary resources',
        'processing_image_succeed': 'Processing to image succeed',
        'processing_image_failed': 'Processing to image failed',
        'processing_video_succeed': 'Processing to video succeed',
        'processing_video_failed': 'Processing to video failed',
        'model_download_not_done': 'Download of the model is not done',
        'model_file_not_present': 'File of the model is not present',
        'select_image_source': 'Select an image for source path',
        'select_image_or_video_target': 'Select an image or video for target path',
        'select_file_or_directory_output': 'Select an file or directory for output path',
        'no_source_face_detected': 'No source face detected',
        'frame_processor_not_loaded': 'Frame processor {frame_processor} could not be loaded',
        'frame_processor_not_implemented': 'Frame processor {frame_processor} not implemented correctly',
        'ui_layout_not_loaded': 'UI layout {ui_layout} could not be loaded',
        'ui_layout_not_implemented': 'UI layout {ui_layout} not implemented correctly',
        'stream_not_loaded': 'Stream {stream_mode} could not be loaded',
        'donate_button_label': 'Donate',
        'start_button_label': 'Start',
        'stop_button_label': 'Stop',
        'clear_button_label': 'Clear',
        'benchmark_runs_checkbox_group_label': 'Benchmark Runs',
        'benchmark_results_dataframe_label': 'Benchmark Results',
        'benchmark_cycles_slider_label': 'Benchmark Cycles',
        'execution_providers_checkbox_group_label': 'Execution Providers',
        'execution_thread_count_slider_label': 'Execution Thread Count',
        'execution_queue_count_slider_label': 'Execution Queue Count',
        'face_analyser_order_dropdown_label': 'Face Analyser Direction',
        'face_analyser_age_dropdown_label': 'Face Analyser Age',
        'face_analyser_gender_dropdown_label': 'Face Analyser Gender',
        'face_selector_mode_dropdown_label': 'Face Selector Mode',
        'face_detector_model_dropdown_label': 'Face Detection Model',
        'face_detector_size_dropdown_label': 'Face Detection Size',
        'face_detector_score_slider_label': 'Face Detection Score',
        'reference_face_gallery_label': 'Reference Face',
        'reference_face_distance_slider_label': 'Reference Face Distance',
        'face_mask_types_checkbox_group_label': 'Face Mask Type',
        'face_mask_blur_slider_label': 'Face Mask Blur',
        'face_mask_padding_top_slider_label': 'Face Mask Padding Top',
        'face_mask_padding_bottom_slider_label': 'Face Mask Padding Bottom',
        'face_mask_padding_left_slider_label': 'Face mask Padding Left',
        'face_mask_padding_right_slider_label': 'Face Mask Padding Right',
        'face_mask_region_checkbox_group_label': 'Face Mask Regions',
        'video_memory_strategy_dropdown_label': 'Video Memory Strategy',
        'max_memory_slider_label': 'Max Memory',
        'output_image_or_video_label': 'Output',
        'output_path_textbox_label': 'Output Path',
        'output_image_quality_slider_label': 'Output Image Quality',
        'output_video_encoder_dropdown_label': 'Output Video Encoder',
        'output_video_preset_dropdown_label': 'Output Video Preset',
        'output_video_quality_slider_label': 'Output Video Quality',
        'output_video_resolution_dropdown_label': 'Output Video Resolution',
        'output_video_fps_slider_label': 'Output Video FPS',
        'preview_image_label': 'Preview',
        'preview_frame_slider_label': 'Preview Frame',
        'frame_processor_not_found': 'Frame processor {frame_processor} not found',
        'frame_processors_checkbox_group_label': 'Frame Processors',
        'face_swapper_model_dropdown_label': 'Face Swapper Model',
        'face_enhancer_model_dropdown_label': 'Face Enhancer Model',
        'face_enhancer_blend_slider_label': 'Face Enhancer Blend',
        'frame_enhancer_model_dropdown_label': 'Frame Enhancer Model',
        'frame_enhancer_blend_slider_label': 'Frame Enhancer Blend',
        'face_debugger_items_checkbox_group_label': 'Face Debugger Items',
        'common_options_checkbox_group_label': 'Options',
        'temp_frame_format_dropdown_label': 'Temp Frame Format',
        'temp_frame_quality_slider_label': 'Temp Frame Quality',
        'trim_frame_start_slider_label': 'Start Frame',
        'trim_frame_end_slider_label': 'End Frame',
        'source_file_label': 'Source',
        'target_file_label': 'Target',
        'webcam_image_label': 'Webcam',
        'webcam_mode_radio_label': 'Webcam Mode',
        'webcam_resolution_dropdown': 'Resolution',
        'webcam_fps_slider': 'Webcam FPS',
        'point': '.',
        'comma': ',',
        'colon': ':',
        'question_mark': '?',
        'exclamation_mark': '!'
    }


def get(key: str) -> str:
    return WORDING[key]
